name: cycler_controller
description: Controller for the Cycler robot developed for Waste Management.
version: 1.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_blue: ^0.6.2
  flutter_spinkit: "^4.0.0"
  flutter_launcher_icons: "^0.7.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  image_path_ios: "assets/images/ios_icon.png"
  image_path_android: "assets/images/android_icon.png"
  ios: true
  android: true
